# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run ProxyCollector

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:

  run:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GithubApiToken: ${{ secrets.GITHUB_TOKEN }}
      GithubUser: ${{ github.repository_owner }}
      GithubRepo: ProxyCollector
      Timeout: 5000
      MaxThreadCount: 96
      SingboxPath: sing-box
      V2rayFormatResultPath: sub/proxies.txt
      SingboxFormatResultPath: sub/singbox.json
      Sources: |
          https://raw.githubusercontent.com/qjlxg/my/refs/heads/main/sc/all.yaml
          https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/list_raw.txt
          https://raw.githubusercontent.com/qjlxg/aggregator/refs/heads/main/ss.txt
          https://raw.githubusercontent.com/qjlxg/ha/refs/heads/main/data/all_unique_nodes.txt
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Install sing-box
      run: |
        curl -fsSLO https://github.com/SagerNet/sing-box/releases/download/v1.10.6/sing-box_1.10.6_linux_amd64.deb
        sudo dpkg -i sing-box_1.10.6_linux_amd64.deb
        sudo apt-get install -f
    - name: Restore dependencies
      run: dotnet restore
    - name: Run
      run: dotnet run --configuration Release --project ProxyCollector
