# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run ProxyCollector

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:

  run:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GithubApiToken: ${{ secrets.GITHUB_TOKEN }}
      GithubUser: ${{ github.repository_owner }}
      GithubRepo: ProxyCollector
      Timeout: 5000
      MaxThreadCount: 96
      SingboxPath: sing-box
      V2rayFormatResultPath: sub/proxies.txt
      SingboxFormatResultPath: sub/singbox.json
      Sources: |
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_AE.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_AR.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_AU.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_BR.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_CA.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_CH.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_CL.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_CO.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_DE.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_DK.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_EE.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_ES.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_FI.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_FR.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_False.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_GB.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_HK.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_ID.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_IN.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_IT.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_JP.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_KR.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_MX.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_MY.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_NL.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_NZ.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_PH.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_RU.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_SA.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_SE.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_SG.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_TH.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_TR.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_TW.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_US.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_VN.meta.yml
        https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/snippets/nodes_ZA.meta.yml
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Install sing-box
      run: |
        curl -fsSLO https://github.com/SagerNet/sing-box/releases/download/v1.10.6/sing-box_1.10.6_linux_amd64.deb
        sudo dpkg -i sing-box_1.10.6_linux_amd64.deb
        sudo apt-get install -f
    - name: Restore dependencies
      run: dotnet restore
    - name: Run
      run: dotnet run --configuration Release --project ProxyCollector
